# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  PROJECT: switchboard

tasks:
  cluster-up:
    cmds:
      - kind create cluster --config=infra/local/kind/config.yaml

  cluster-down:
    cmds:
      - kind delete cluster --name "{{.PROJECT}}"

  kustomize-template:
    cmds:
      - kubectl kustomize infra/k8s/overlays/local

  kustomize-apply:
    cmds:
      - kubectl apply -k infra/k8s/overlays/local

  keycloak-portforward:
    cmds:
      - kubectl config set-context --current --namespace={{.PROJECT}}
      - kubectl port-forward svc/switchboard-keycloak-service 8080:8080

  keycloak-validate:
    cmds: 
      - |
        curl -s -X POST http://localhost:8080/realms/switchboard/protocol/openid-connect/token \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "grant_type=password" \
        -d "client_id=switchboard" \
        -d "username=user1" \
        -d "password=password" \
        | jq -r .access_token \
        | cut -d. -f2 \
        | awk '{ pad=length($0)%4; if(pad==2) print $0"=="; else if(pad==3) print $0"="; else print $0 }' \
        | base64 -d \
        | jq .