# This should be encrypted with SOPS,etc or injected with ESO
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: switchboard
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin