---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-community
  namespace: switchboard
spec:
  interval: 1m
  url: https://grafana-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: switchboard
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: '12.3.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: switchboard
      interval: 10m
  values:
    persistence:
      enabled: true
      volumeName: grafana-volume