---
apiVersion: v1
data:
  password: dGVzdHBhc3N3b3Jk
  username: dGVzdHVzZXI=
kind: Secret
metadata:
  creationTimestamp: "2026-04-25T01:36:16Z"
  name: keycloak-db-secret
  namespace: default
  resourceVersion: "2344"
  uid: c9a22693-c25f-4f2d-99bb-046e2088328e
type: Opaque
---