apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: switchboard-keycloak
spec:
  instances: 1
  # env:
  #   - name: KC_LOG_LEVEL
  #     value: debug
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    httpEnabled: true
    httpPort: 8080
  hostname:
    strict: false